### ISSUE TITLE
关于文章翻译认领拖动不到 In progress 列表的问题

### ISSUE THREAD

**Issue by anxk** [jenkins-infra/wechat#276]
在翻译文章认领的看板 https://github.com/orgs/jenkins-zh/projects/2 无法从 To do 列表拖动到 In progress  列表，我感觉可能是一般用户没有权限，因为看了好久的社区相关说明，没有找到相应内容。如果是的话，这个该怎么解决？

**Comment by anxk** [comment]
ping @LinuxSuRen

**Comment by LinuxSuRen** [comment]
@anxk  感谢您的反馈，我已经给您发了邀请。确认没问题后，麻烦在这里回复一下。谢谢您在社区的贡献。

**Comment by anxk** [comment]
已经加入，为社区贡献也是自己学习和提升的重要途径，不用客气。:)

**Comment by LinuxSuRen** [comment]
共同进步！！！
