### ISSUE TITLE
公众号争取早日开通评论功能

### ISSUE THREAD

**Issue by donhui** [jenkins-infra/wechat#57]
定个小目标：公众号争取早日开通评论功能

**Comment by LinuxSuRen** [comment]
新注册的公众号已经关闭了这个功能，但是中文社区网站中的[文章](https://jenkins-zh.cn/wechat/articles/2019/04/2019-04-03-the-benefits-and-challenges-of-continuous-integration/)下面可以评论。可能好多人还不知道这个。

**Comment by donhui** [comment]
> 新注册的公众号已经关闭了这个功能，但是中文社区网站中的[文章](https://jenkins-zh.cn/wechat/articles/2019/04/2019-04-03-the-benefits-and-challenges-of-continuous-integration/)下面可以评论。可能好多人还不知道这个。

还是公众号有这个功能好，可以互动。
没有这个功能，略忧伤。

**Comment by LinuxSuRen** [comment]
微信公众号太封闭了，没有办法。
